version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=032383812007.dkr.ecr.us-west-2.amazonaws.com/ida-pre-registers
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo REPOSITORY_URI $REPOSITORY_URI
      - echo NODE_ENV $NODE_ENV
      - echo IDA_BASE_URI $IDA_BASE_URI
      - docker build --build-arg NODE_ENV=$NODE_ENV --build-arg IDA_BASE_URI=$IDA_BASE_URI -t ida-pre-registers-prod:latest .
      - docker tag ida-pre-registers-prod:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - echo Changing the Dockerrun file to the correct for this environment
      - sed -i 's/DUMMY_ENV/'$NODE_ENV'/g' Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json
    - .ebextensions/*

