branch-defaults:
  master:
    environment: web-production
environment-defaults:
  web-production:
    branch: null
    repository: null
global:
  application_name: som
  default_ec2_keyname: web-prod
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Docker running on
    64bit Amazon Linux/2.12.16
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
